// @ts-check
import eslint from '@eslint/js'
import stylistic from '@stylistic/eslint-plugin'

const jsFiles = ['**/*.{js,mjs,cjs,jsx}']

const ignores = [
  '**/node_modules/**',
  '**/.git/**',
  '**/.hg/**',
  '**/.svn/**',
  '**/dist/**',
  '**/build/**',
  '**/coverage/**',
  '**/.cache/**',
  '**/.eslintcache',
  '**/.next/**',
  '**/.nuxt/**',
  '**/.astro/**',
  '**/.output/**',
  '**/.svelte-kit/**',
  '**/.turbo/**',
  '**/.vite/**',
  '**/storybook-static/**',
  '**/tmp/**',
  '**/temp/**',
]

const withJsFiles = config => ({
  ...config,
  files: jsFiles,
})

export default [
  {
    ignores,
  },
  {
    files: jsFiles,
    languageOptions: {
      ecmaVersion: 'latest',
    },
  },
  {
    ...eslint.configs.recommended,
    files: jsFiles,
  },
  withJsFiles(stylistic.configs['disable-legacy']),
  withJsFiles(stylistic.configs.recommended),
  {
    files: jsFiles,
    rules: {
      'func-style': ['error', 'expression', { allowArrowFunctions: true }],
      'array-callback-return': 'error',
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-await-in-loop': 'warn',
      'no-class-assign': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'warn',
      'no-constructor-return': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-unassigned-vars': 'warn',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable': 'warn',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'warn',
      'no-unused-private-class-members': 'warn',
      'no-unused-vars': 'warn',
      'no-use-before-define': 'error',
      'no-useless-assignment': 'warn',
      'require-atomic-updates': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'block-scoped-var': 'error',
      complexity: ['error', 3],
      'consistent-return': 'off',
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': 'off',
      eqeqeq: 'error',
      'max-classes-per-file': ['error', 3],
      'max-depth': ['error', 3],
      'max-nested-callbacks': ['error', 4],
      'max-params': ['error', 4],
      'no-alert': 'error',
      'no-case-declarations': 'off',
      'no-console': 'off',
      'no-delete-var': 'error',
      'no-div-regex': 'error',
      'no-implied-eval': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-useless-return': 'off',
      'no-var': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-rest-params': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      curly: ['error', 'multi'],
      '@stylistic/array-bracket-newline': ['error', { multiline: true }],
      '@stylistic/array-element-newline': ['error', { multiline: true }],
      '@stylistic/arrow-parens': ['error', 'as-needed'],
      '@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
      '@stylistic/linebreak-style': ['error', 'unix'],
      '@stylistic/multiline-comment-style': ['error', 'bare-block'],
      '@stylistic/no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
      '@stylistic/nonblock-statement-body-position': ['error', 'beside'],
    },
  },
]
