// @ts-check
import eslint from '@eslint/js'
import prettierRecommended from 'eslint-plugin-prettier/recommended'

import internal from './plugins/index.js'

const jsFiles = ['**/*.{js,mjs,cjs,jsx}']
const prettierPrintWidth = 85

const ignores = [
  '**/node_modules/**',
  '**/.git/**',
  '**/.github/**',
  '**/.hg/**',
  '**/.svn/**',
  '**/dist/**',
  '**/build/**',
  '**/coverage/**',
  '**/.cache/**',
  '**/.eslintcache',
  '**/.next/**',
  '**/.nuxt/**',
  '**/.astro/**',
  '**/.wrangler/**',
  '**/.output/**',
  '**/.vite/**',
  '**/.idea/**',
  '**/storybook-static/**',
  '**/tmp/**',
  '**/.tmp/**',
  '**/temp/**',
]

const withJsFiles = config => ({
  ...config,
  files: jsFiles,
})

export default [
  {
    ignores,
  },
  {
    files: jsFiles,
    languageOptions: {
      ecmaVersion: 'latest',
    },
    plugins: {
      '@unix': internal,
    },
  },
  {
    ...eslint.configs.recommended,
    files: jsFiles,
  },
  {
    files: jsFiles,
    rules: {
      'func-style': ['error', 'expression', { allowArrowFunctions: true }],
      'array-callback-return': 'error',
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-await-in-loop': 'warn',
      'no-class-assign': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'warn',
      'no-constructor-return': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-unassigned-vars': 'warn',
      'no-undef': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable': 'warn',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'warn',
      'no-unused-private-class-members': 'warn',
      'no-unused-vars': 'warn',
      'no-use-before-define': 'error',
      'no-useless-assignment': 'warn',
      'require-atomic-updates': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'block-scoped-var': 'error',
      complexity: ['error', 3],
      'consistent-return': 'off',
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': 'off',
      eqeqeq: 'error',
      'max-classes-per-file': ['error', 3],
      'max-depth': ['error', 3],
      'max-nested-callbacks': ['error', 4],
      'max-params': ['error', 5],
      'no-alert': 'error',
      'no-case-declarations': 'off',
      'no-console': 'off',
      'no-delete-var': 'error',
      'no-div-regex': 'error',
      'no-implied-eval': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-useless-return': 'off',
      'no-var': 'error',
      'prefer-rest-params': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      '@unix/function-blank-lines': 'error',
      '@unix/compact-nonblock-statement': [
        'error',
        { maxLineLength: prettierPrintWidth },
      ],
      '@unix/compact-return-if': 'error',
    },
  },
  withJsFiles(prettierRecommended),
]
